### ISSUE TITLE
rake db:seed throws error

### ISSUE THREAD

**Issue by danielmackey** [bellycard/napa#162]
```sh
bundle exec rake db:seed
#=> rake db:seedNameError: uninitialized constant Napa::ActiveRecordSeeder
```

**Comment by brandonweiss** [comment]
Is this still an issue? It's working fine for me. `Napa::ActiveRecordSeeder` is required in the `Rakefile` and 0a42064e589c9f79aedb58c32fac40b6ab654be9 looks good...

**Comment by danielmackey** [comment]
@brandonweiss, you are correct. this does indeed work with ruby gems version. I believe when I submitted this bug, the code was only on the master branch and the latest version hadn't be cut.

**Comment by brandonweiss** [comment]
🎉
