### ISSUE TITLE
Roar and Honeybadger updated, breaking default scaffold setup

### ISSUE THREAD

**Issue by rdavidso** [bellycard/napa#180]
The Gemfile contains just `roar` and `honeybadger` packages, both of which updated with breaking changes recently.  When doing a `rake db:reset` command, for example, the output is
```
rake aborted!
LoadError: cannot load such file -- roar/representer/json
```
with a stacktrace behind it.  Rolling only roar back then causes Rake to have a similar issue with honeybadger.

Setting roar to `'~> 0.12.0'` and honeybadger to `'~> 1.16.7'` seems to fix the problem.

**Comment by danielmackey** [comment]
@bellycard/platform, i just encountered this too when starting a project from scratch.
