### ISSUE TITLE
Gemspec versions off?

### ISSUE THREAD

**Issue by ianneub** [bellycard/napa#203]
https://github.com/bellycard/napa/blob/master/napa.gemspec#L27

From a fresh install of napa, running `bundle install` results in Grape 0.11.0 being used.

Is that really the version that Napa intended?

I think the line above should read:
```ruby
gem.add_dependency 'grape', '~> 0.9.0'
```

As well as the other dependencies.

If you agree, I can create a quick PR.

**Comment by shaqq** [comment]
@ianneub great catch! Totally on board.

Overall, we need to dig deeper into the gems we use (by default scaffolds and Napa itself). This is a solid step towards that.
