### ISSUE TITLE
ActiveModel ForbiddenAttributesProtection causing ForbiddenAttributesError on API POST

### ISSUE THREAD

**Issue by hstrowd** [bellycard/napa#205]
As noted in https://github.com/intridea/grape/issues/404, without the 'hashie-forbidden_attributes' grape is unable to process post attributes due to ActiveModel's ForbiddenAttributesProtection#sanitize_for_mass_assignment method. It seems like adding the hashie-forbidden_attributes gem to the 'new' template's Gemfile would be a nice way to provide this functionality out of the box for new services.

**Comment by shaqq** [comment]
closed by #206
