### ISSUE TITLE
.env file keeps getting overwriten

### ISSUE THREAD

**Issue by alexandru-calinoiu** [bellycard/napa#230]
I am trying out a pilot project but I can't get past `rake db:migrate` my `.env` file keeps getting overwritten and the old file gets stored in `.env_conflict-20150910-220455`

**Comment by umtrey** [comment]
Hi @alexandru-calinoiu - do you have your code posted somewhere for us to take a look? A conflict file makes it seem like it's a git issue, but it's hard to know.

**Comment by alexandru-calinoiu** [comment]
The repo is here https://github.com/alexandru-calinoiu/contact-service

Steps to reproduce:
- clone
- update the user or the password in .env
- run `rake db:migrate`

In about 10s you will get a .env_conflict file ...

**Comment by alexandru-calinoiu** [comment]
It actually seems to happen with all . (dot) files, I can reproduce it with `.env` `.rubocop.yml`

**Comment by alexandru-calinoiu** [comment]
Also not a git issue for sure it happened before I could get `git init` to run.

**Comment by alexandru-calinoiu** [comment]
On further investigation running any rake command including `rake -T` will trigger the weird behaviour, napa commands seem to be fine.

**Comment by alexandru-calinoiu** [comment]
No luck with this one, I've tried all I could think of and all my (dot) files keep reseting, even if they are commited.

**Comment by alexandru-calinoiu** [comment]
I can't seem to reproduce somewhere else so I will leave it as it is for now
