### ISSUE TITLE
Ruby version hardcoded to 2.0.0

### ISSUE THREAD

**Issue by ochagata** [bellycard/napa#247]
Is there a reason why the ruby version in the generated gemfile and `.ruby-version` is locked at 2.0.0?

I suggest removing the restriction and letting the user set it to what they wish.

@darbyfrey

**Comment by danielmackey** [comment]
+!

**Comment by darbyfrey** [comment]
What do you guys think about this approach instead? https://github.com/bellycard/napa/pull/232

**Comment by ochagata** [comment]
:+1: It applies to all version managers(rvm, chruby, rbenv)

I'll make an updated PR in a few minutes and we can close out #232 and #249
